CREATE TABLE  "EMPLOYEES" 
   (	"EMP_ID" VARCHAR2(20), 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50) NOT NULL ENABLE, 
	"EMP_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(20), 
	"DEPT_ID" VARCHAR2(50), 
	 CHECK (role IN ('Admin', 'Employee')) ENABLE, 
	 PRIMARY KEY ("EMP_ID") ENABLE, 
	 UNIQUE ("USERNAME") ENABLE, 
	 CONSTRAINT "FK_EMPLOYEE_DEPARTMENT" FOREIGN KEY ("DEPT_ID")
	  REFERENCES  "DEPARTMENT" ("DEPT_ID") ENABLE
   )