CREATE TABLE  "LEAVE_APPLICATIONS" 
   (	"LEAVE_ID" NUMBER, 
	"EMP_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"LEAVE_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE NOT NULL ENABLE, 
	"REASON" VARCHAR2(255), 
	"STATUS" VARCHAR2(20) DEFAULT 'Pending', 
	 PRIMARY KEY ("LEAVE_ID") ENABLE, 
	 CONSTRAINT "FK_LEAVE_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES  "EMPLOYEES" ("EMP_ID") ON DELETE CASCADE ENABLE
   )