CREATE TABLE  "SALARY_LEDGER" 
   (	"EMP_ID" VARCHAR2(50), 
	"BASIC_SALARY" NUMBER(10,2) NOT NULL ENABLE, 
	"ALLOWANCE" NUMBER(10,2) DEFAULT 0.00, 
	"DEDUCTIONS" NUMBER(10,2) DEFAULT 0.00, 
	"NET_SALARY" NUMBER(10,2), 
	 PRIMARY KEY ("EMP_ID") ENABLE, 
	 CONSTRAINT "FK_SALARY_EMP" FOREIGN KEY ("EMP_ID")
	  REFERENCES  "EMPLOYEES" ("EMP_ID") ON DELETE CASCADE ENABLE
   )